version: '3'

services:
  # nginx
  nginx:
    image: nginx:alpine
    container_name: nginx
    network_mode: host
    ports:
      - "80:80"
    volumes:
      - ./nginx/www:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d 
      - ./nginx/log:/var/log/nginx

  cerbot:
    depends_on:
      - nginx
    image: certbot/certbot
    network_mode: host
    volumes:
      - ./certbot-etc:/etc/letsencrypt
      - ./nginx/www:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email youremail --agree-tos --no-eff-email --staging -d example.com -d www.example.com
