version: '3'

services:
  # v2ray
  v2ray:
    image: v2ray/official:latest
    container_name: v2ray
    restart: always
    networks:
      - v2ray
    volumes:
      - ./v2ray:/etc/v2ray
      - ./v2ray/log:/etc/v2ray/log/v2ray

  # web server
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    networks:
      - v2ray
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # root
      - ./nginx/www:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot-etc:/etc/nginx/ca
      - ./nginx/log:/var/log/nginx
    links:
      - v2ray
    
  # certbot
  certbot:
    depends_on:
      - nginx
    image: certbot/certbot
    network_mode: host
    volumes:
      - ./certbot-etc:/etc/letsencrypt
      - ./nginx/www:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email youremail --agree-tos --no-eff-email --force-renewal -d example.com -d www.example.com

networks:
  v2ray:
